# Generated by Django 5.0.4 on 2024-04-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_name', models.CharField(max_length=30)),
                ('location', models.CharField(choices=[('DU', 'Dublin'), ('LI', 'limerick'), ('KI', 'kildare')], max_length=100)),
                ('bike_description', models.TextField(max_length=500)),
                ('bike_model_year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], verbose_name='year')),
                ('price', models.IntegerField()),
                ('no_of_owners', models.IntegerField()),
                ('colour', models.CharField(max_length=30)),
                ('bike_image_1', models.ImageField(upload_to='media/')),
                ('bike_image_2', models.ImageField(upload_to='media/')),
                ('bike_image_3', models.ImageField(upload_to='media/')),
                ('seating_capacity', models.IntegerField(choices=[('5', 'five-seater'), ('7', 'seven-seater'), ('9', 'nine-seater')], verbose_name='seat')),
                ('is_feautured', models.BooleanField(default='False')),
            ],
        ),
    ]
