# Generated by Django 5.0.4 on 2024-04-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='is_feautured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='seating_capacity',
            field=models.CharField(choices=[('5', 'five-seater'), ('7', 'seven-seater'), ('9', 'nine-seater')], max_length=30, verbose_name='seat'),
        ),
    ]
