# Generated by Django 5.0.4 on 2024-04-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_alter_bikes_is_feautured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='location',
            field=models.CharField(choices=[('Dublin', 'Dublin'), ('Limerick', 'limerick'), ('Kildare', 'kildare')], max_length=100),
        ),
    ]
